### ISSUE TITLE
upgrade to v5.58

### ISSUE THREAD

**Issue by rsubr** [jirutka/stunnel-static#1]
Thanks a ton for this repo! I needed a static stunnel binary to run in a locked down environment and your repo made it very easy. I manually ran the steps from build.sh in an alpine docker container compiled v5.58 release.

Can you please update the repo and release v5.58? Thanks!

 - https://www.stunnel.org/downloads.html
 - https://www.stunnel.org/downloads/stunnel-5.58.tar.gz

**Comment by jirutka** [comment]
I just updated it, https://github.com/jirutka/stunnel-static/releases/tag/v5.58-r0.

**Comment by 0neday** [comment]
do not work on cross compile for armv7

**Comment by jirutka** [comment]
> do not work on cross compile for armv7

WAT? The binary is now compiled for x86_64 only.

**Comment by 0neday** [comment]
> > do not work on cross compile for armv7
> 
> WAT? The binary is now compiled for x86_64 only.

I mean use -all-static option for cross compile for arm is not success

**Comment by jirutka** [comment]
> I mean use -all-static option for cross compile for arm is not success

And how is it related to this project? Consult it with the stunnel project (https://www.stunnel.org/support.html), not here.

**Comment by 0neday** [comment]
I do, no reply
